version: '3.3'
services:
  saltestracker-db:
    image: mysql:5.7
    restart: always
    container_name: saltestracker-db
    environment:
      MYSQL_DATABASE: 'saltestracker-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - saltestracker-db:/var/lib/mysql
volumes:
  saltestracker-db:

